#!/usr/bin/env bash

dbus_session_file=~/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-$display_number
suppress_warnings="no"

if [ -e "$dbus_session_file" ]; then
  . "$dbus_session_file"
  export DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID
fi

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK 

source $HOME/.profile

exec urxvtd -f &
exec conky -c $HOME/.conkyrc &
exec conky -c $HOME/.calconkyrc &
exec xsetroot -solid black &
exec xscreensaver &

exec dbus-launch --sh-syntax --exit-with-session $HOME/.cabal/bin/xmonad
